# Generated by Django 5.1.7 on 2025-04-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume')),
                ('title', models.CharField(max_length=100, verbose_name='Titlu')),
                ('photo', models.ImageField(upload_to='volunteers/', verbose_name='Fotografie')),
                ('bio', models.TextField(verbose_name='Biografie')),
                ('category', models.CharField(choices=[('nutritionist', 'Nutriționist'), ('medic', 'Medic'), ('specialist', 'Specialist'), ('coordonator', 'Coordonator'), ('student', 'Student')], default='nutritionist', max_length=50, verbose_name='Categorie')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Voluntarii cu prioritate mare vor apărea primii', verbose_name='Prioritate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
            ],
            options={
                'verbose_name': 'Voluntar',
                'verbose_name_plural': 'Voluntari',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
