# Generated by Django 5.1.7 on 2025-04-19 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=250)),
                ('full_description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='ebooks/covers/')),
                ('file', models.FileField(upload_to='ebooks/files/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_free', models.BooleanField(default=False)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB')], default='pdf', max_length=10)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks', to='ebook.category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
