# Generated by Django 5.1.7 on 2025-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='author',
        ),
        migrations.AddField(
            model_name='ebook',
            name='authors',
            field=models.ManyToManyField(related_name='authored_ebooks', to='users.profile', verbose_name='Autori'),
        ),
    ]
