# Generated by Django 5.1.7 on 2025-04-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_remove_ebook_author_ebook_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='toc',
            field=models.TextField(default='', verbose_name='Cuprins'),
            preserve_default=False,
        ),
    ]
