# Generated by Django 5.1.7 on 2025-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the post', null=True, upload_to='posts/'),
        ),
    ]
