# Generated by Django 5.1.7 on 2025-04-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_on_landing',
            field=models.BooleanField(default=False, help_text='Check to display this post on the main landing page', verbose_name='Show on Landing Page'),
        ),
    ]
