# Generated by Django 5.1.7 on 2025-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_show_on_landing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='Upload an image for the post', upload_to='posts/'),
        ),
    ]
